scrape_configs:
  - job_name: 'MyAppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'resource_catalog:5000' ]
        labels:
          application: 'resource_catalog'
      - targets: [ 'service_catalog:8082' ]
        labels:
          application: 'service_catalog'
      - targets: [ 'chart_service:5003' ]
        labels:
          application: 'chart_service'
      - targets: [ 'recommendation_service:8081' ]
        labels:
          application: 'recommendation_service'