services:
  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./logs/loki:/etc/loki
    command: -config.file=/etc/loki/config.yml
    networks:
      - tjp-net

  promtail:
    image: grafana/promtail:2.8.2
    container_name: promtail
    volumes:
      - ./Microservices/chart_service/logs:/var/log
      - ./Microservices/gemini/logs:/var/log
      - ./Microservices/image_recognition/logs:/var/log
      - ./Microservices/recommendation_service/logs:/var/log
      - ./Microservices/ThingSpeak_adaptor/logs:/var/log
      - ./Microservices/vase_control/logs:/var/log
      - ./Microservices/catalog_expose/logs/resource_service:/var/log
      - ./Microservices/catalog_expose/logs/service_catalog:/var/log
      - ./logs/promtail:/etc/promtail
    command: -config.file=/etc/promtail/config.yml
    networks:
      - tjp-net

networks:
  tjp-net:
    driver: bridge
